# Run Jest on PR
name: Test
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19
      - run: npm install
      - run: npm test
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CLIENT_SIGNING_SECRET: ${{ secrets.CLIENT_SIGNING_SECRET }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
